name: MyToken Docker Action
description: Github Action to obtain an OIDC access token form a MyToken secret
author: Karlsruhe Institute of Technology

inputs:
  my-token:
    description: My token to use to retrieve the access token
    required: true

outputs:
  access-token:
    description: The access token to use in future requests

runs:
  using: docker
  image: Dockerfile
  env:
    MY_TOKEN: ${{ inputs.my-token }}
  args:
    - "--MT--env=MY_TOKEN"
