name: MyToken Action
description: Github Action to obtain an OIDC access token form a MyToken secret
author: Karlsruhe Institute of Technology

inputs:
  my-token:
    description: My token to use to retrieve the access token
    required: true

outputs:
  access-token:
    description: The access token to use in future requests
    value: ${{ steps.get-access-token.outputs.access-token }}

runs:
  using: composite
  steps:
    - id: get-access-token
      shell: bash
      run: |
        ACCESS_TOKEN=$(curl --request POST \
          --url https://mytoken.data.kit.edu/api/v0/token/access \
          --header 'Content-Type: application/json' \
          --data '{
            "comment": "Access Token for Github Actions",
            "grant_type": "mytoken",
            "mytoken": "${{ inputs.my-token }}"
        }' | jq -r .access_token)
        echo "access-token=$ACCESS_TOKEN" >> $GITHUB_OUTPUT
