on:
  workflow_dispatch:

jobs:
  get-access_token:
    runs-on: ubuntu-latest
    name: Get Access Token Test
    steps:
      - id: get-access-token
        uses: BorjaEst/mytoken-docker-action@0.1.0
        with:
          my-token: ${{ secrets.MYTOKEN }}
      - id: validate-access-token
        run: |
          curl --request GET \
          --url https://aai.eosc-portal.eu/oidc/userinfo \
          --header 'Authorization: Bearer ${{ steps.get-access-token.outputs.access_token }}'
