on:
  workflow_dispatch:

jobs:
  get-access_token:
    runs-on: ubuntu-latest
    name: Get Access Token Test
    steps:
      - name: Obtain Access Token
        id: at
        uses: BorjaEst/mytoken-docker-action@0.0.1
        with:
          my-token: ${{ secrets.MYTOKEN }}
      - name: Indicate that the access token was retireved
        run: echo "The access token was retireved"
